name: Rebuild Index
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Restore cache
      id: cache
      uses: actions/cache@v3
      with:
        path: |
          ~/quicklisp
          ~/.wine
          ~/trial-deployment
          ~/.sbclrc
        key: ${{ runner.os }}
        restore-keys: ${{ runner.os }}
    - name: Install packages
      run: |
        git config --global user.name "CI"
        git config --global user.email "shinmera@tymoon.eu"
        sudo apt-get update
        sudo apt-get -qq install wine curl fontforge imagemagick inkscape --no-install-recommends
    - name: Install env
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        git clone --depth 1 https://gitea.tymoon.eu/Shirakumo/trial-deployment.git ~/trial-deployment
        curl -o ~/quicklisp.lisp https://beta.quicklisp.org/quicklisp.lisp
        ~/trial-deployment/sbcl-lin \
             --load ~/quicklisp.lisp \
             --eval '(quicklisp-quickstart:install)' \
             --eval '(ql-util:without-prompting (ql:add-to-init-file))' \
             --eval '(ql:quickload :shasht)' \
             --eval '(ql:quickload :clip)' \
             --eval '(ql:quickload :pathname-utils)' \
             --quit
        ~/trial-deployment/sbcl-win \
             --load ~/quicklisp.lisp \
             --eval '(quicklisp-quickstart:install)' \
             --eval '(ql-util:without-prompting (ql:add-to-init-file))' \
             --eval '(ql:quickload :shasht)' \
             --eval '(ql:quickload :clip)' \
             --eval '(ql:quickload :pathname-utils)' \
             --quit
    - uses: actions/checkout@v2
    - name: Rebuild
      run: |
        ~/trial-deployment/sbcl-lin \
              --noinform \
              --disable-debugger \
              --eval "(ql:quickload '(clip shasht pathname-utils) :silent T)" \
              --load "compile.lisp" \
              --eval '(promptfont-compiler::all)'
    - name: GH Pages deploy
      if: github.head_ref == null
      run: |
        git clone -q --branch=gh-pages https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git ~/gh-pages
        cp $FILES ~/gh-pages/
        git -C ~/gh-pages add $FILES
        git -C ~/gh-pages commit -qm "CI index rebuild." || echo "Nothing to commit."
        git -C ~/gh-pages push -q origin gh-pages
      env:
        FILES: |
          index.html
          index.css
