name: Rebuild Index
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      run: |
        git config --global user.name "CI"
        git config --global user.email "shinmera@tymoon.eu"
        sudo apt-get -qq install sbcl curl fontforge imagemagick inkscape
        curl -o ~/quicklisp.lisp https://beta.quicklisp.org/quicklisp.lisp
        sbcl --load ~/quicklisp.lisp \
             --eval '(quicklisp-quickstart:install)' \
             --eval '(ql-util:without-prompting (ql:add-to-init-file))' \
             --eval '(ql:quickload :shasht)' \
             --eval '(ql:quickload :clip)' \
             --eval '(ql:quickload :pathname-utils)' \
             --quit
    - uses: actions/cache@v3
      with:
        path: |
          ~/quicklisp/
        key: ${{ runner.os }}
        restore-keys: ${{ runner.os }}
    - uses: actions/checkout@v1
    - name: Rebuild
      run: |
        ./compile.lisp
    - name: GH Pages deploy
      if: github.head_ref == null
      run: |
        git clone -q --branch=gh-pages https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git ~/gh-pages
        cp $FILES ~/gh-pages/
        git -C ~/gh-pages add $FILES
        git -C ~/gh-pages commit -qm "CI index rebuild." || echo "Nothing to commit."
        git -C ~/gh-pages push -q origin gh-pages
      env:
        FILES: LICENSE.txt README.md index.html index.css glyphs.json chars.txt promptfont.ttf promptfont.otf promptfont.css atlas-android.png atlas-gamepad.png atlas-icons.png atlas-keyboard.png atlas-mouse.png
