name: Rebuild Index

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install sbcl
      run: |
        sudo apt-get -qq update | true
        sudo apt-get -qq install sbcl curl
    - name: Install Quicklisp
      run: |
        curl -o ~/quicklisp.lisp https://beta.quicklisp.org/quicklisp.lisp
        sbcl --load ~/quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(ql-util:without-prompting (ql:add-to-init-file))' --quit
    - name: Rebuild the index
      run: |
        ./compile.lisp
    - name: GH Pages deploy
      if: github.head_ref == null
      run: |
        git config --global user.name "CI"
        git config --global user.email "shinmera@tymoon.eu"
        git clone --quiet --branch=gh-pages https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git ~/gh-pages
        cp $FILES ~/gh-pages/
        git -C ~/gh-pages add $FILES
        git -C ~/gh-pages commit -qm "CI index rebuild." || echo "Nothing to commit."
        git -C ~/gh-pages push -q origin gh-pages
      env:
        FILES: index.html glyphs.json chars.txt PromptFont.ttf PromptFont.otf
